### ISSUE TITLE
Vytvořit materiály na testovací pyworking

### ISSUE THREAD

**Issue by hroncok** [pyvec/pyworking-materials#16]

**Comment by zoellenka** [comment]
prosím o anotaci nejlépe do konce týdne...

**Comment by encukou** [comment]
Materiály: https://github.com/pyvec/pyworking-materials/tree/master/180324_Testovani
Přendání na naucse: https://github.com/pyvec/naucse.python.cz/issues/358

Můžu tohle zavřít?
